from transformers import AutoTokenizer

# Load JinaAI Tokenizer
tokenizer = AutoTokenizer.from_pretrained("jinaai/jina-embedding-s-en-v1")

# Given text
text = """Y ou have learnt about the preparation of financial statements for a sole proprietary concern. As the business expands, one needs more capital and larger number of people to manage the business and share its risks. In such a situation, people usually adopt the partnership form of organisation. Accounting for partnership firms has it’s own peculiarities, as the partnership firm comes into existence when two or more persons come together to establish business and share its profits. On many issues affecting distribution of profits, there may not be any specific agreement between the partners. In such a situation the provisions of the Indian Partnership Act 1932 apply. Similarly, calculation of interest on capital, interest on drawings and maintenance of partners capital accounts have their own peculiarities. Not only that a variety of adjustments are required on the death of a partner or when a new partner is admitted and so on. These peculiar situations need specific treatment in accounting that need to be clarified. The present chapter discusses some basic aspects of partnership such as distribution of profit, maintenance of capital accounts, etc. The treatment of situations like admission of partner, retirement, death and dissolution have been taken up in the subsequent chapters. 1.1 Nature of Partnership When two or more persons join hands to set up a business and share its profits and losses, they are said to be in partnership. Section 4 of the Indian Partnership Act 1932 defines partnership as the LEARNING OBJECTIVES After studying this chapter, you will be able to: Define partnership and list its essential features; Identify the provisions of the Indian Partnership Act 1932 that are relevant for accounting; Prepare partners’ capital accounts under fixed and fluctuating capital methods; Explain the distribution profit or loss among the partners and prepare the Profit and Loss Appropriation Account; Calculate interest on capital and drawing under various situations; Explain how guarantee for a minimum amount of profit affects the distribution of profits among the partners; Make necessary adjustments to rectify the past errors in partners capital accounts; and Prepare final accounts of a partnership firm; Accounting for Partnership: Basic Concepts 1 2024-25 2 Accountancy – Partnership Accounts ‘relation between persons who have agreed to share the profits of a business carried on by all or any of them acting for all’. Persons who have entered into partnership with one another are individually called ‘partners’ and collectively called ‘firm’. The name under which"""

# Tokenize the text
tokens = tokenizer.encode(text, add_special_tokens=False)

# Print token count
print(f"Total Tokens: {len(tokens)}")
